"""Stage 2.5 global consolidation edits, applied AFTER consolidate.py --write.
Every merge/collapse/cut is logged to the run's decisions.jsonl / dropped.jsonl."""
import json, sys, os
sys.path.insert(0,'scripts')
import run_store as R
run=open('work/genetics/run_dir.txt').read().strip()
P='work/genetics/chapter_11_cards.json'
cards=json.load(open(P))
def find(block, needle):
    for i,c in enumerate(cards):
        if c.get('block')==block and needle in c['Text']:
            return i
    raise SystemExit(f"not found: {block} / {needle}")
log=[]
# 1) rule 12: D5's 'cannot initiate by themselves' (mark 45, p287) is the same fact as D4's
#    'all eukaryotic polymerases require transcription factors to initiate' (mark 38, p286).
a=find('U10_eukaryotic_polymerases','require the assistance of other proteins')
b=find('U12a_pol2_promoter_elements','cannot::can or cannot')
keep, drop = cards[a], cards[b]
keep['from_idx']=sorted(set(keep['from_idx'])|set(drop['from_idx']))
keep['verified_against']+=" | p287 (mark 45, merged rule 12): 'Unlike their prokaryotic counterparts, eukaryotic RNA polymerases cannot initiate transcription by themselves. All five eukaryotic RNA polymerases require the assistance of protein transcription factors to start the synthesis of an RNA chain.'"
keep['Back Extra']=keep['Back Extra']+"<br><br>Pitfall: basal transcription factors are required for initiation to happen at all; enhancers and silencers, with still other transcription factors, only modulate how efficiently a promoter initiates."
keep['verified_by']+="; consolidation: merged with the mark-45 card (same fact, rule 12)"
keep['_figure_request']=keep.get('_figure_request') or 'FIGURE 11.14'
R.record(run,'decisions.jsonl',{"stage":"consolidate","kind":"merge","kept_block":keep['block'],"dropped_block":drop['block'],"marks":[38,45],
  "why":"rule 12 same-fact duplicate: 'eukaryotic RNA polymerases cannot initiate by themselves' (mark 45, p287) and 'all eukaryotic RNA polymerases require transcription factors to initiate' (mark 38, p286) are one claim; kept the three-blank p286 card (all / transcription factors / initiate), cited mark 45 on it, carried the p287 quote and D5's Pitfall line; mark 45 stays covered."})
R.record(run,'dropped.jsonl',{"stage":"consolidate","unit":drop.get('_unit'),"block":drop['block'],"kind":"drop","why":"rule 12 duplicate of the mark-38 card (merged; mark 45 now cited there)","card_obj":drop})
del cards[b]
log.append(f"merged {drop['block']} into {keep['block']}")
# 2) check 16: D6's poly(A) polymerase stem said 'After endonucleolytic cleavage creates the 3' end', which hands D4's
#    'generated by {{cleavage}} rather than termination' answer to anyone who has seen it. Cleavage moves to the back.
c=find('U14_polyA_polymerase_tail','poly(A) polymerase}}')
old=cards[c]['Text']
cards[c]['Text']=old.replace("After endonucleolytic cleavage creates the 3′ end of a eukaryotic transcript, the enzyme","Once the 3′ end of a eukaryotic transcript has been generated, the enzyme")
assert cards[c]['Text']!=old, old
cards[c]['Back Extra']=cards[c]['Back Extra'].replace("Mechanism: the cut that creates the 3′ end","Mechanism: the 3′ end is made by endonucleolytic cleavage first; the cut")
cards[c]['verified_by']+="; consolidation: 'after cleavage' moved off the front (check 16: it answered the sibling card that tests cleavage-vs-termination)"
R.record(run,'decisions.jsonl',{"stage":"consolidate","kind":"edit","block":cards[c]['block'],"why":"check 16 cross-card give-away: the visible 'after endonucleolytic cleavage' answered the D4 card that clozes 'cleavage rather than termination'; reworded to 'once the 3′ end has been generated', cleavage kept on the back"})
log.append("D6 poly(A) polymerase stem de-leaked")
for i,cd in enumerate(cards): cd['_unit_idx']=i
json.dump(cards, open(P,'w'), indent=1, ensure_ascii=False)
print("\n".join(log)); print("cards now:", len(cards))
